// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0v0hpXxj2XNsSZCCzK8gfniylH2CC7uM',
    appId: '1:881076436397:web:7329afdff95b25687d7524',
    messagingSenderId: '881076436397',
    projectId: 'yne-django-dev',
    authDomain: 'yne-django-dev.firebaseapp.com',
    storageBucket: 'yne-django-dev.appspot.com',
    measurementId: 'G-CTT7JDJ1WB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTjaOA3ryZ28y8HX8FyeK92ZiJ1DcB1xo',
    appId: '1:881076436397:android:d4b4a500bc40b8727d7524',
    messagingSenderId: '881076436397',
    projectId: 'yne-django-dev',
    storageBucket: 'yne-django-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt6y-2BCziPS9dOJouzBvLsD9YjBisEyY',
    appId: '1:881076436397:ios:d7c29eb861794f187d7524',
    messagingSenderId: '881076436397',
    projectId: 'yne-django-dev',
    storageBucket: 'yne-django-dev.appspot.com',
    iosClientId: '881076436397-tlak2mnd7kia9cvvn8dlub5j4pq7jdv9.apps.googleusercontent.com',
    iosBundleId: 'com.example.yneFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt6y-2BCziPS9dOJouzBvLsD9YjBisEyY',
    appId: '1:881076436397:ios:d7c29eb861794f187d7524',
    messagingSenderId: '881076436397',
    projectId: 'yne-django-dev',
    storageBucket: 'yne-django-dev.appspot.com',
    iosClientId: '881076436397-tlak2mnd7kia9cvvn8dlub5j4pq7jdv9.apps.googleusercontent.com',
    iosBundleId: 'com.example.yneFlutter',
  );
}
